- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: create file
      shell: echo hello world `date` by `hostname` >>/root/hello.log

